---
- name: Download file 
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /latest.tar.gz

- name: Extract tar
  unarchive:
    src: /latest.tar.gz
    dest: /var/www/html
    remote_src: yes
    extra_opts: [--strip-components=1]

#- name: Copy wp-config
#  template: src=wp-config.php dest=/var/www/html/wp-config.php